---
- name: configure mailman
  template:
    src: mm_cfg.py.j2
    dest: /etc/mailman/mm_cfg.py
    owner: root
    group: root
    mode: 0644
  notify:
  - restart mailman

- name: create mailman srv directory
  file:
    state: directory
    dest: /srv/mailman/lists.noisebridge.net
    owner: www-data
    group: www-data
