---

- name: configure mailman
  replace:
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    dest: "/etc/mailman/mm_cfg.py"
  with_items:
    - { regexp: "^DEFAULT_URL_PATTERN = 'http://(%s)/'",  replace: "DEFAULT_URL_PATTERN = 'https://%s'" }
    - { regexp: "^DEFAULT_EMAIL_HOST = '.*'",  replace: "DEFAULT_EMAIL_HOST = '{{ mailman.domain }}'" }
    - { regexp: "^DEFAULT_URL_HOST   = '.*'",  replace: "DEFAULT_URL_HOST = '{{ mailman.domain }}'" }
  tags:
    - mailman

- name: configure postfix mailman user
  blockinfile:
    dest: /etc/postfix/master.cf
    block: |
      mailman   unix  -       n       n       -       -       pipe
        flags=FR user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py
        ${nexthop} ${user}
  tags:
    - postfix
    - mailman

- name: create postfix transport maps file
  copy:
    dest: /etc/postfix/transport
    group: root
    owner: root
    content: "{{ mailman.domain }}      mailman:"
  tags:
    - postfix
    - mailman

- name: configure postfix transport maps
  lineinfile:
    dest: /etc/postfix/main.cf
    line: 'transport_maps = hash:/etc/postfix/transport'
  tags:
    - postfix
    - mailman

- name: run postmap on transport 
  command: "/usr/sbin/postmap -v /etc/postfix/transport"
  tags:
    - postfix
    - mailman
  notify:
    restart postfix
