---
  - name: install mailman
    apt: name=mailman state=latest update_cache=yes cache_valid_time=3600
    tags:
      - mailman
      - apt
 
  - name: create /srv directory
    file:
      dest: /srv/{{ mailman.domain }}
      state: directory
      owner: root
      group: root
    tags:
      - mailman
 
  - name: install http and https virtualhosts 
    template:
      src: "apache_{{ item }}.conf"
      dest: "/etc/apache2/sites-available/{{ mailman.domain }}-{{ item }}.conf"
      owner: root
      group: root
    with_items: 
      - http
      - https
    tags:
      - apache
      - mailman
    notify:
      - reload-apache

  - name: enable virtualhosts
    file:
      src: "/etc/apache2/sites-available/{{ mailman.domain}}-{{ item }}.conf"
      dest: "/etc/apache2/sites-enabled/{{ mailman.domain}}-{{ item }}.conf"
      state: link
      owner: root
      group: root
    with_items: 
      - http
      - https
    tags:
     - apache
     - mailman
    notify:
     - reload-apache

  - name: configure mailman
    replace:
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
      dest: "/etc/mailman/mm_cfg.py"
    with_items:
      - { regexp: "^DEFAULT_URL_PATTERN = 'http://(%s)/'",  replace: "DEFAULT_URL_PATTERN = 'https://%s'" }
      - { regexp: "^DEFAULT_EMAIL_HOST = '.*'",  replace: "DEFAULT_EMAIL_HOST = '{{ mailman.domain }}'" }
      - { regexp: "^DEFAULT_URL_HOST   = '.*'",  replace: "DEFAULT_URL_HOST = '{{ mailman.domain }}'" }
    tags:
     - mailman
      
  - name: configure postfix mailman user
    blockinfile:
      dest: /etc/postfix/master.cf
      block: |
        mailman   unix  -       n       n       -       -       pipe
          flags=FR user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py
          ${nexthop} ${user}
    tags:
      - postfix
      - mailman

  - name: create postfix transport maps file
    copy:
      dest: /etc/postfix/transport
      group: root
      owner: root
      content: "{{ mailman.domain }}      mailman:"
    tags:
      - postfix
      - mailman
    
  - name: configure postfix transport maps
    lineinfile:
      dest: /etc/postfix/main.cf
      line: 'transport_maps = hash:/etc/postfix/transport'
    tags:
      - postfix
      - mailman

  - name: run postmap on transport 
    command: "/usr/sbin/postmap -v /etc/postfix/transport"
    tags:
      - postfix
      - mailman
    notify:
      restart postfix
