---
- name: install Caddy binary
  copy:
    src: caddy
    dest: /usr/local/bin/caddy
    owner: root
    group: root
    mode: 0755
  tags:
    - caddy

- name: install caddy.service file
  copy:
    src: caddy.service
    dest: /etc/systemd/system/caddy.service
    group: root
    owner: root
  tags:
    - caddy
