---
 - name: install unattended-upgrades
   items:
     - unattended-upgrades
     - apt-listchanges
   apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
   tags:
     - security

 - name: configure debian stable upgrades
   replace:
     dest: /etc/apt/apt.conf.d/50unattended-upgrades
     regexp: '(\/\/\s+)"o=Debian,a=stable";'
     replace: '        "o=Debian,a=stable";'
   tags:
     - security
     
 - name: configure debian stable-update upgrades
   replace:
     dest: /etc/apt/apt.conf.d/50unattended-upgrades
     regexp: '(\/\/\s+)"o=Debian,a=stable-updates";'
     replace: '        "o=Debian,a=stable-updates";'
   tags:
     - security

 - name: mail root an unattended upgrade
   replace:
     dest: /etc/apt/apt.conf.d/50unattended-upgrades
     regexp: '/\/\Unattended-Upgrade::Mail "root";'
     replace: 'Unattended-Upgrade::Mail "root";'
   tags:
     - security

 - name: enable unattended upgrade
   copy:
     dest: /etc/apt/apt.conf.d/20auto-upgrades
     src: 20auto-upgrades 
   tags:
     - security

 - name: install logwatch & sendmail
   items:
     - logwatch
     - sendmail
   apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
   tags:
     - security
     - logwatch

 - name: configure daily logwatch email
   copy:
     src: 00logwatch
     dest: /etc/cron.daily/00logwatch
   tags:
     - security

 - name: install fail2ban
   apt: name=fail2ban state=latest update_cache=yes cache_valid_time=3600
   tags:
     - security

 - name: install sudo & pwgen
   apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
   items:
     - sudo
     - pwgen
   tags:
     - security

 - name: add admin users
   with_items: "{{ admins }}"
   user:
     name: "{{ item }}"
     groups: sudo

 - name: add admin users .ssh/ directories
   with_items: "{{ admins }}"
   file:
     dest: "/home/{{ item }}/.ssh"
     state: directory
     owner: "{{ item }}"
     group: "{{ item }}"
       
 - name: add admin user ssh keys
   with_items: "{{ admins }}"
   copy:
     src: "group_files/{{ item }}.pub"
     dest: "/home/{{ item }}/.ssh/authorized_keys"
     owner: "{{ item }}"
     group: "{{ item }}"

 - name: generate passwords for admin users
   with_items: "{{ admins }}"
   shell: "/usr/bin/pwgen -s 32 1 > /home/{{ item }}/password.txt"
   args:
     creates: "/home/{{ item }}/password.txt"
   become: yes
   become_user: "{{ item }}"

 - name: set admin passwords
   with_items: "{{ admins }}"
   shell: "echo {{ item }}:$(echo -n `cat /home/{{ item }}/password.txt`) | chpasswd"
   args:
     creates: "/home/{{ item }}/.password_set"

 # stop clobbering passwords
 - name: set password-set file
   with_items: "{{ admins }}"
   copy:
     dest: "/home/{{ item }}/.password_set"
     owner: "{{ item }}"
     group: "{{ item }}"
     content: ""
   tags:
     - security

 - name: disable ssh root login
   replace: dest=/etc/ssh/sshd_config regexp='PermitRootLogin (.*)' replace='PermitRootLogin no'
   notify: reload-ssh
   tags:
     - security

 - name: disable ssh password authentication
   replace: dest=/etc/ssh/sshd_config regexp='(\#?)PasswordAuthentication (.*)' replace='PasswordAuthentication no'
   notify: reload-ssh
   tags:
     - security

 - name: install tlsdate
   apt: package=tlsdate state=latest update_cache=yes cache_valid_time=3600
   tags:
     - security

 - name: enable tlsdate debian
   service: name=tlsdated state=started enabled=yes
   when: ansible_distribution == "Debian"
   tags:
     - security

 - name: enable tlsdate ubuntu
   service: name=tlsdate state=started enabled=yes
   when: ansible_distribution == "Ubuntu"
   tags:
     - security

