---
  - name: install debian backports
    apt_repository:
      repo: "deb http://httpredir.debian.org/debian jessie-backports main contrib"
      state: present
      update_cache: yes
    tags:
      - apt
