# docker-compose.yml

version: "3.6"

volumes:
  nextcloud:
    name: nextcloud
  nextcloud_apps:
    name: nextcloud_apps
  nextcloud_config:
    name: nextcloud_config
  nextcloud_data:
    name: nextcloud_data
  nextcloud_theme:
    name: nextcloud_theme
  nextcloud_db:
    name: nextcloud_db

services:
  app:
    container_name: nextcloud
    # Do not pull 'latest'  list the exact image needed
    #image: nextcloud:13.0.6-apache
    #image: nextcloud:14.0.2-apache
    image: nextcloud:14.0.2-rc-apache
    restart: unless-stopped
    networks:
      - nextcloud
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_apps:/var/www/html/custom_apps
      - nextcloud_config:/var/www/html/config
      - nextcloud_data:/var/www/html/data
      - nextcloud_theme:/var/www/html/themes
    ports:
      - 80:80
    labels:
      - traefik.enable=false
      - traefik.frontend.rule=Host:cloud.noisebridge.net
#      - traefik.docker.network=public-web
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.STSSeconds=31536000

  db:
    container_name: nextcloud_db
    image: mariadb
    restart: unless-stopped
    volumes:
      - nextcloud_db:/var/lib/mysql
      - ./mariadb:/etc/mysql/mariadb.conf.d
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      # not sure if this is needed:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - nextcloud
    labels:
      - traefik.enable=false

  redis:
    container_name: nextcloud_redis
    image: redis
    restart: unless-stopped
    networks:
      - nextcloud
    labels:
     - traefik.enable=false

  cron:
    container_name: nextcloud_cron
     #image: nextcloud:13.0.6-apache
    image: nextcloud:14.0.2-rc-apache
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
    networks:
     - nextcloud
    labels:
     - traefik.enable=false

networks:
  nextcloud:
    name: nextcloud
#  public-web:  # until I get traefik running
#    external: true
