# docker-compose.yml

# running Nextcloud version 13

version: "3.5"

volumes:
  nextcloud_db:
    name: nextcloud_db
  nextcloud:
    name: nextcloud

services:
  app:
    container_name: nextcloud
#    Dont pull 'latest'.  be specifc with what version you want
#    image: nextcloud:13.0.4-apache
#    image: nextcloud:13.0.5-apache
    image: nextcloud:13.0.6-apache
    restart: unless-stopped
    labels:
      - traefik.enable=false # for now, until i get traefik running
      - traefik.frontend.rule=Host:cloud.noisebridge.net
      - traefik.docker.network=public-web
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.STSSeconds=31536000
    networks:
      - nextcloud
#      - public-web # disabled until I get traefik running
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
    ports:
      - 80:80

  db:
    container_name: nextcloud_db
    image: mariadb
    restart: unless-stopped
    volumes:
      - nextcloud_db:/var/lib/mysql
      - ./mariadb:/etc/mysql/mariadb.conf.d
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      # not sure if this is needed:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - nextcloud
    labels:
      - traefik.enable=false

  redis:
    container_name: nextcloud_redis
    image: redis
    restart: unless-stopped
    networks:
      - nextcloud

  cron:
    container_name: nextcloud_cron
    image: nextcloud:13.0.6-apache
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
    networks:
     - nextcloud
    labels:
     - traefik.enable=false

networks:
#  public-web:  # until I get traefik running
#    external: true
  nextcloud:
    name: nextcloud
