---
- name: Install packages
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce

- name: make directory to store docker-compose files
  file:
    dest: "/srv/docker"
    state: directory
    owner: root
    group: root
