---
- name: Install packages
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
  - ack-grep
  - apt-transport-https
  - bash-completion
  - ca-certificates
  - curl
  - debconf
  - debconf-utils
  - file
  - git
  - htop
  - iftop
  - inotify-tools
  - iotop
  - less
  - lsof
  - mosh
  - mtr-tiny
  - screen
  - strace
  - sudo
  - tcpdump
  - vim
