---
- name: Install packages
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
  - ack-grep
  - apt-transport-https
  - bash-completion
  - bind9-host
  - ca-certificates
  - curl
  - debconf
  - debconf-utils
  - dnsutils
  - file
  - git
  - htop
  - iftop
  - inotify-tools
  - iotop
  - less
  - libcap2-bin
  - lsof
  - mosh
  - mtr-tiny
  - screen
  - strace
  - sudo
  - tcpdump
  - vim

- name: Setup sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%sudo"
    line: "%sudo	ALL=(ALL:ALL) NOPASSWD: ALL"
    state: present
