---
 - name: install certbot
   apt:
     name: certbot
     state: latest
     update_cache: yes
     cache_valid_time: 3600
     default_release: "jessie-backports"
   tags:
     - certbot
     - apt

 - name: ensure that all srv directories exist
   file: 
     dest: "/srv/{{ item.key }}"
     state: directory
     owner: www-data
     group: www-data
   with_dict: "{{ certbot_certs }}"
   tags:
     - certbot

 - name: request certificates
   command: "certbot certonly --agree-tos -n -m hostmaster@{{ item.key }} --webroot -w /srv/{{ item.key }} -d {{ item.value|join(' -d ') }} --expand"
   args:
     creates: "/etc/letsencrypt/live/{{ item.key }}/cert.pem"
   with_dict: "{{ certbot_certs }}"
   tags:
     - certbot
