---
- name: install dependencies
  apt:
    state: latest
    package: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - imagemagick
  - php7.0
  - php7.0-mysql
  - php7.0-imagick
  - php7.0-fpm
  - php7.0-mbstring
  - php7.0-xml
  tags:
  - apt
  - mediawiki

- name: fetch mediawiki LTS release
  get_url:
    dest: /tmp/
    url: "https://releases.wikimedia.org/mediawiki/{{ mediawiki.version | regex_search('\\d+.\\d+') }}/mediawiki-{{ mediawiki.version }}.tar.gz"
    checksum: "sha256:{{ mediawiki.version_sha256sum }}"
  tags:
  - mediawiki

- name: make wiki directory
  file:
    dest: "/srv/mediawiki/{{ mediawiki.domain }}"
    state: directory
    owner: www-data
    group: www-data
  tags:
  - mediawiki

- name: extract mediawiki
  unarchive:
    src: "/tmp/mediawiki-{{ mediawiki.version }}.tar.gz"
    dest: "/srv/mediawiki/{{ mediawiki.domain }}"
    remote_src: true
    extra_opts: ["--strip-components=1"]
  tags:
  - mediawiki

- name: install StopForumSpam
  git:
    repo: 'https://github.com/wikimedia/mediawiki-extensions-StopForumSpam.git'
    dest: "/srv/mediawiki/{{ mediawiki.domain }}/extensions/StopForumSpam"
    version: "REL1_27"
  tags:
  - mediawiki

- name: install LocalSettings
  template:
    src: LocalSettings.php
    dest: "/srv/mediawiki/{{ mediawiki.domain }}/LocalSettings.php"
    owner: www-data
    group: www-data
  tags:
  - mediawiki
